substitutions:
  name: ${room|replace(' ','-')}-mini-split-thread
  friendly_name: ${room|title} Mini Split Thread
  # Homeassistant sensor providing remote temperature
  remote_temp_sensor: sensor.${room|replace(' ','_')}_mini_split_remote_temperature
  mitsubishi_cn105_esphome_version: v1.6.6

packages:
  - !include ../common/base.yaml
  - !include ../common/boards/esp32-c6.yaml
  - !include ../common/thread.yaml
  - !include ../common/mitsubishi-cn105.yaml
